<h3 style="display:inline">Content-based Collaborative Filtering:</h3><h4 style="display:inline; margin-left:-40px;">Food Recommender System Case Study</h4>

<b>freemium_datascience/machine-learning-tutorials/Unsupervised Learning/Practice
/Recommender-System-Case-Study-Practice.ipynb</b>

In this case study, you are asked to develop a food recommender system using content-based filtering. You are given records of different types of food recipes, and rating users have given on these recipes. Your task consist of 

<ol>
    <li>Building a food recommender engine that suggests top similar recipes to a given product</li>
    <li>Estimating a user rating on a recipe he has never tasted</li>
</ol>

<b style="color:blue">Step 1. Load the datasets</b>

In [39]:
import pandas as pd

food_df=pd.read_csv('../datasets/food_recommender_datasets/1662574418893344.csv')
food_df.head(10)

,Food_ID,Name,C_Type,Veg_Non,Describe
0,1,summer squash salad,Healthy Food,veg,"white balsamic vinegar, lemon juice, lemon rin..."
1,2,chicken minced salad,Healthy Food,non-veg,"olive oil, chicken mince, garlic (minced), oni..."
2,3,sweet chilli almonds,Snack,veg,"almonds whole, egg white, curry leaves, salt, ..."
3,4,tricolour salad,Healthy Food,veg,"vinegar, honey/sugar, soy sauce, salt, garlic ..."
4,5,christmas cake,Dessert,veg,"christmas dry fruits (pre-soaked), orange zest..."
5,6,japanese curry arancini with barley salsa,Japanese,veg,"japanese curry, sticky rice, cheese inside ric..."
6,7,chocolate nero cookies,Dessert,veg,"almonds, eggs, granulated sugar, bittersweet c..."
7,8,lamb and chargrilled bell pepper soup,Healthy Food,non-veg,"lamb bones (preferably shank and shoulder), on..."
8,9,cream of almond soup,Healthy Food,veg,"vegetable stock, skimmed milk, toasted almonds..."
9,10,broccoli and almond soup,Healthy Food,veg,"vegetable stock, broccoli, ground almonds (toa..."

<h3>Preprocessing and Future Extraction</h3><br/>
<b style="color:blue">Step 2. Verify whether there are missing values and Impute data/Remove rows if necessary</b>

In [40]:
food_df.isna().any(axis=1).sum()

0

<b style="color:blue">Step 3. Remove unwanted characters and put every word to lower case </b>

In [41]:
import re

food_df0 = food_df.copy()
food_df['Describe'] = food_df['Describe'].apply(lambda x:re.sub(r'[(),/]','',x).lower())
food_df['Name'] = food_df['Name'].apply(lambda x:x.lower())
food_df['C_Type'] = food_df['C_Type'].apply(lambda x:x.lower())
food_df.head()

,Food_ID,Name,C_Type,Veg_Non,Describe
0,1,summer squash salad,healthy food,veg,white balsamic vinegar lemon juice lemon rind ...
1,2,chicken minced salad,healthy food,non-veg,olive oil chicken mince garlic minced onion sa...
2,3,sweet chilli almonds,snack,veg,almonds whole egg white curry leaves salt suga...
3,4,tricolour salad,healthy food,veg,vinegar honeysugar soy sauce salt garlic clove...
4,5,christmas cake,dessert,veg,christmas dry fruits pre-soaked orange zest le...

<b style="color:blue">Step 4. Transform C_type using One Hot Encoding on C-Type </b>

In [42]:
food_df = pd.get_dummies(food_df,columns=['C_Type'])

<b style="color:blue">Step 5. Transform Veg_Non to a binary variable </b>

In [43]:
food_df['Veg_Non']=food_df['Veg_Non'].apply(lambda x:1 if x=='veg'else 0)

In [44]:
food_df.head()

,Food_ID,Name,Veg_Non,Describe,C_Type_ korean,C_Type_beverage,C_Type_chinese,C_Type_dessert,C_Type_french,C_Type_healthy food,C_Type_indian,C_Type_italian,C_Type_japanese,C_Type_korean,C_Type_mexican,C_Type_nepalese,C_Type_snack,C_Type_spanish,C_Type_thai,C_Type_vietnames
0,1,summer squash salad,1,white balsamic vinegar lemon juice lemon rind ...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,2,chicken minced salad,0,olive oil chicken mince garlic minced onion sa...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,3,sweet chilli almonds,1,almonds whole egg white curry leaves salt suga...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,4,tricolour salad,1,vinegar honeysugar soy sauce salt garlic clove...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,christmas cake,1,christmas dry fruits pre-soaked orange zest le...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

<b style="color:blue">Step 6. Vectorise Describe using TF-IDF and check the new data shape</b>

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(analyzer='word', ngram_range=(1,1),
                     min_df=0.0, stop_words='english')
tf_feats_describe = tf.fit_transform(food_df['Describe'])
tf_feats_describe.shape

(400, 1250)

<b style="color:blue">Step 7. Vectorise Name using TF-IDF and check the new data shape</b>

In [46]:
tf = TfidfVectorizer(analyzer='word', ngram_range=(1,1),
                     min_df=0.0, stop_words='english')
tf_feats_name = tf.fit_transform(food_df['Name'])
tf_feats_name.shape

(400, 588)

<b style="color:blue">Step 8. Transform Describe and Name TD-IF feautures using PCA</b>
n_components = 10. Use 'from sklearn.decomposition import TruncatedSVD'

In [47]:
from sklearn.decomposition import TruncatedSVD

n_pc = 10
pca_describe = TruncatedSVD(n_components=10)#10 principal components
tf_feats_describe_pca = pca_describe.fit_transform(tf_feats_describe)
tf_feats_desc_df = pd.DataFrame(tf_feats_describe_pca,columns=['pca_desc_%d'%(i) for i in range(n_pc)])
tf_feats_desc_df.head()

,pca_desc_0,pca_desc_1,pca_desc_2,pca_desc_3,pca_desc_4,pca_desc_5,pca_desc_6,pca_desc_7,pca_desc_8,pca_desc_9
0,0.283839,-0.061333,-0.267870,-0.267778,0.100699,-0.106324,0.068454,0.058020,0.015958,-0.086264
1,0.390965,-0.112235,-0.415879,0.143358,-0.148613,0.039532,-0.009740,-0.006132,-0.121839,-0.009669
2,0.318375,0.104125,0.063746,-0.029375,0.063405,-0.099467,-0.148862,-0.167702,-0.204847,0.063023
3,0.234772,-0.093199,-0.206863,0.115357,-0.017633,0.008820,0.000618,0.053372,-0.100876,0.008431
4,0.089116,0.164581,-0.045401,-0.053308,0.047349,0.086109,0.159599,0.103556,0.046662,-0.068094

In [48]:
tf_feats_desc_df.shape

(400, 10)

In [49]:
n_pc = 10
pca_name = TruncatedSVD(n_components=10)#10 principal components
tf_feats_name_pca = pca_name.fit_transform(tf_feats_name)
#tf_feats_describe.shape
tf_feats_name_df = pd.DataFrame(tf_feats_name_pca,columns=['pca_name_%d'%(i) for i in range(n_pc)])
tf_feats_name_df.head()

,pca_name_0,pca_name_1,pca_name_2,pca_name_3,pca_name_4,pca_name_5,pca_name_6,pca_name_7,pca_name_8,pca_name_9
0,0.036853,0.020117,-0.032003,0.002890,-0.072765,0.400934,-0.290302,0.130601,0.122342,-0.184456
1,0.340199,-0.077470,-0.041035,-0.005998,-0.058615,0.312930,-0.273826,0.079233,0.071607,-0.209206
2,0.056968,0.023146,0.008852,0.003700,-0.019431,0.056577,0.031568,-0.094888,-0.015309,0.017422
3,0.033037,0.007047,-0.022705,0.006287,-0.080730,0.389862,-0.317577,0.109222,0.115627,-0.248622
4,0.006806,0.014841,-0.018983,0.450078,-0.433751,-0.208567,-0.154585,0.099028,-0.031740,-0.000423

In [50]:
tf_feats_name_df.shape

(400, 10)

<b style="color:blue">Step 9. Merge all columns - pca_features, food_id, veg and c_types into a new feature dataframe</b>

In [51]:
food_feats_df = pd.concat([food_df.drop(columns=['Name','Describe']),tf_feats_desc_df,tf_feats_name_df],axis=1)
food_feats_df.head()

,Food_ID,Veg_Non,C_Type_ korean,C_Type_beverage,C_Type_chinese,C_Type_dessert,C_Type_french,C_Type_healthy food,C_Type_indian,C_Type_italian,...,pca_name_0,pca_name_1,pca_name_2,pca_name_3,pca_name_4,pca_name_5,pca_name_6,pca_name_7,pca_name_8,pca_name_9
0,1,1,0,0,0,0,0,1,0,0,...,0.036853,0.020117,-0.032003,0.002890,-0.072765,0.400934,-0.290302,0.130601,0.122342,-0.184456
1,2,0,0,0,0,0,0,1,0,0,...,0.340199,-0.077470,-0.041035,-0.005998,-0.058615,0.312930,-0.273826,0.079233,0.071607,-0.209206
2,3,1,0,0,0,0,0,0,0,0,...,0.056968,0.023146,0.008852,0.003700,-0.019431,0.056577,0.031568,-0.094888,-0.015309,0.017422
3,4,1,0,0,0,0,0,1,0,0,...,0.033037,0.007047,-0.022705,0.006287,-0.080730,0.389862,-0.317577,0.109222,0.115627,-0.248622
4,5,1,0,0,0,1,0,0,0,0,...,0.006806,0.014841,-0.018983,0.450078,-0.433751,-0.208567,-0.154585,0.099028,-0.031740,-0.000423

In [52]:
food_feats_df.columns

Index(['Food_ID', 'Veg_Non', 'C_Type_ korean', 'C_Type_beverage',
       'C_Type_chinese', 'C_Type_dessert', 'C_Type_french',
       'C_Type_healthy food', 'C_Type_indian', 'C_Type_italian',
       'C_Type_japanese', 'C_Type_korean', 'C_Type_mexican', 'C_Type_nepalese',
       'C_Type_snack', 'C_Type_spanish', 'C_Type_thai', 'C_Type_vietnames',
       'pca_desc_0', 'pca_desc_1', 'pca_desc_2', 'pca_desc_3', 'pca_desc_4',
       'pca_desc_5', 'pca_desc_6', 'pca_desc_7', 'pca_desc_8', 'pca_desc_9',
       'pca_name_0', 'pca_name_1', 'pca_name_2', 'pca_name_3', 'pca_name_4',
       'pca_name_5', 'pca_name_6', 'pca_name_7', 'pca_name_8', 'pca_name_9'],
      dtype='object')

<b style="color:blue">Step 10. Build the similarity matrix</b>

In [53]:
from sklearn.metrics.pairwise import cosine_similarity 

food_feats_df_clean = food_feats_df.drop(columns=['Food_ID'])
cosine_sim_matrix = cosine_similarity(food_feats_df_clean,food_feats_df_clean)
cosine_sim_matrix.shape

(400, 400)

In [54]:
cosine_sim_matrix

array([[1.        , 0.68075599, 0.44124772, ..., 0.05773732, 0.03383861,
        0.91048725],
       [0.68075599, 1.        , 0.05579402, ..., 0.08384868, 0.0494502 ,
        0.59990793],
       [0.44124772, 0.05579402, 1.        , ..., 0.04055171, 0.03133823,
        0.47869927],
       ...,
       [0.05773732, 0.08384868, 0.04055171, ..., 1.        , 0.00592259,
        0.07252443],
       [0.03383861, 0.0494502 , 0.03133823, ..., 0.00592259, 1.        ,
        0.02319003],
       [0.91048725, 0.59990793, 0.47869927, ..., 0.07252443, 0.02319003,
        1.        ]])

<b style="color:blue">Step 11. Suggest Top N similar Food Recipes for a given recipe</b>

<b>1. Given the similarity matrix create a function that returns a sorted list of food-ids and names in descending order of similarities given only the food_id</b>

The returned dataframe must have three columns: food_id, name, description, similarity

In [55]:
import numpy as np

def top_food_resemblance(food_id,cosine_matrix,food_df):
        num_foods = len(food_df)
        if food_id > num_foods or food_id < 1:
            raise ValueError('incorrect food id')
        
        sort_ids = np.argsort(cosine_matrix[food_id-1])
        sort_ids=sort_ids[::-1]#reverse sorting order
        similarity_vals = cosine_matrix[food_id-1][sort_ids]
        food_df_tmp = food_df.iloc[sort_ids,:]
        output_df = pd.DataFrame({'food_id':food_df_tmp.Food_ID,'name':food_df_tmp.Name,'describe':food_df_tmp.Describe,'sim':similarity_vals})
        return output_df

<b style="color:blue">Step 12. Call the Function on any food id and return the dataframe with a list of suggestions</b>

In [61]:
food_id = 7
output_df = top_food_resemblance(food_id,cosine_sim_matrix,food_df)
output_df.head(10)

,food_id,name,describe,sim
6,7,chocolate nero cookies,almonds eggs granulated sugar bittersweet choc...,1.000000
236,237,double chocolate easter cookies,butter brown sugar castor sugar vanilla essenc...,0.992700
252,253,double chocolate easter cookies,butter brown sugar castor sugar vanilla essenc...,0.992700
221,222,chocolate fudge cookies,dark chocolate coverture butter sugar eggs flo...,0.990204
50,51,christmas chocolate fudge cookies,unsalted butter brown sugar chocolate chocolat...,0.990163
205,206,chocolate doughnut,sugar egg yolks egg butter yeast milk,0.981257

<b style="color:blue">Step 13.Create a function that will return a user_ID rating for a food_id he has never rated</b>

In [62]:
rating_df = pd.read_csv('../datasets/food_recommender_datasets/ratings.csv')
rating_df.head()

   User_ID  Food_ID  Rating
0      1.0     88.0     4.0
1      1.0     46.0     3.0
2      1.0     24.0     5.0
3      1.0     25.0     4.0
4      2.0     49.0     1.0

<b style="color:blue">Step 14. Rate any food</b>

In [63]:
import warnings
import heapq # <-- Efficient sorting of large lists

def rate_food(user_id,food_id,cosine_matrix,rating_df,food_df,k_thr=10,sim_thr=0.0):
    n_f = len(food_df)
    if food_id > n_f or food_id < 1:
        raise ValueError('food id does not exist')
    neighs = []
    
    
    tmp_frame = rating_df[(rating_df['Food_ID']==food_id) & (rating_df['User_ID']==user_id)]
    if len(tmp_frame) != 0:
        warnings.warn('Food already rated..')
        return tmp_frame.Rating[0]
    else:        
        for index, row in rating_df[rating_df['User_ID']==user_id].iterrows():            
            sim_ij = cosine_matrix[food_id-1,int(row['Food_ID'])-1]
            r_i = row['Rating']
            neighs.append((sim_ij,row['Rating']))
        k_neighbors = heapq.nlargest(k_thr,neighs,key=lambda t:t[0])
        
        #compute weight average
        sim_tot = 0
        weighSum = 0
        for (sim_ij,r_i) in k_neighbors:
            if sim_ij > sim_thr:
                sim_tot+= sim_ij
                weighSum += sim_ij*r_i
        try:
            pred_r = weighSum/sim_tot
        except ZeroDivisionError:
            pred_r = np.mean(rating_df[rating_df['Food_ID']==food_id]['Rating'])  
        pred_r = max(pred_r,0)
        pred_r = min(pred_r,5)
        return pred_r

In [65]:
user_id = 1
food_id = 89

food_record = food_df0[food_df0['Food_ID']==food_id]
food_name = food_record.loc[food_id-1,'Name']
food_descript = food_record.loc[food_id-1,'Describe']

print('Food Details ---\n\n[',food_id,' - ',food_name,']','\n\nDescription:',food_descript,'\n','-'*80,'\n')

rating = rate_food(user_id,food_id,cosine_sim_matrix,rating_df,food_df)
print('Rating for foodID',food_id,'by user',user_id,':',rating)

Food Details ---

[ 89  -  chicken popcorn ]

Description: chicken (boneless), corn flour or all purpose flour, egg, bread crumbs, salt, ginger garlic paste, black pepper, onion powder (optional), red chilli powder or paprika or cayenne pepper, oil for deep frying
 --------------------------------------------------------------------------------

Rating for foodID 89 by user 1 : 3.578329401508485